package njan.flashcardseditor;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jan
 */
public class FlashCardsEditorUI extends javax.swing.JFrame {
    static final String SELECT_SET_TITLE = "Select Card Set";
    static final String SAVE_SET_TITLE = "Save Card Set";
    static final String XML_EXTENSION = ".xml";
    String currentPath = "";
    
    /**
     * Creates new form FlashCardsEditorUI
     */
    public FlashCardsEditorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPath = new javax.swing.JTextField();
        jButtonSave = new javax.swing.JButton();
        jButtonOpen = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelSetName = new javax.swing.JLabel();
        jTextFieldSetName = new javax.swing.JTextField();
        jLabelTextSize = new javax.swing.JLabel();
        jFormattedTextFieldTextSize = new javax.swing.JFormattedTextField();
        jComboBoxCard = new javax.swing.JComboBox<>();
        jButtonDelete = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanelFront = new javax.swing.JPanel();
        jLabelFront = new javax.swing.JLabel();
        jScrollPaneFront = new javax.swing.JScrollPane();
        jTextAreaFront = new javax.swing.JTextArea();
        jPanelBack = new javax.swing.JPanel();
        jLabelBack = new javax.swing.JLabel();
        jScrollPaneBack = new javax.swing.JScrollPane();
        jTextAreaBack = new javax.swing.JTextArea();
        jLabelID = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jButtonApply = new javax.swing.JButton();
        jButtonSaveAs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonOpen.setText("Open");
        jButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOpenActionPerformed(evt);
            }
        });

        jLabelSetName.setText("Set name:");

        jTextFieldSetName.setText("unnamed");

        jLabelTextSize.setText("Text size:");

        jFormattedTextFieldTextSize.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextFieldTextSize.setValue(32f);

        jComboBoxCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCardActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.setEnabled(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jSplitPane1.setDividerLocation(240);
        jSplitPane1.setResizeWeight(0.5);
        jSplitPane1.setName(""); // NOI18N

        jLabelFront.setText("Front:");

        jScrollPaneFront.setMinimumSize(null);

        jTextAreaFront.setEnabled(false);
        jTextAreaFront.setMinimumSize(null);
        jTextAreaFront.setPreferredSize(null);
        jScrollPaneFront.setViewportView(jTextAreaFront);

        javax.swing.GroupLayout jPanelFrontLayout = new javax.swing.GroupLayout(jPanelFront);
        jPanelFront.setLayout(jPanelFrontLayout);
        jPanelFrontLayout.setHorizontalGroup(
            jPanelFrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFrontLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelFrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneFront, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelFrontLayout.createSequentialGroup()
                        .addComponent(jLabelFront)
                        .addGap(0, 179, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelFrontLayout.setVerticalGroup(
            jPanelFrontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFrontLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelFront)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneFront, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanelFront);

        jLabelBack.setText("Back:");

        jScrollPaneBack.setMinimumSize(null);

        jTextAreaBack.setEnabled(false);
        jTextAreaBack.setMinimumSize(null);
        jTextAreaBack.setName(""); // NOI18N
        jTextAreaBack.setPreferredSize(null);
        jScrollPaneBack.setViewportView(jTextAreaBack);

        javax.swing.GroupLayout jPanelBackLayout = new javax.swing.GroupLayout(jPanelBack);
        jPanelBack.setLayout(jPanelBackLayout);
        jPanelBackLayout.setHorizontalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBackLayout.createSequentialGroup()
                        .addComponent(jLabelBack)
                        .addGap(0, 178, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelBackLayout.setVerticalGroup(
            jPanelBackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneBack, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(jPanelBack);

        jLabelID.setText("ID:");

        jTextFieldID.setEnabled(false);

        jButtonApply.setText("Apply");
        jButtonApply.setEnabled(false);
        jButtonApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApplyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSplitPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBoxCard, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelSetName)
                            .addComponent(jLabelTextSize))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldSetName, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldTextSize))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonApply, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSetName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldTextSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTextSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID)
                    .addComponent(jButtonApply)))
        );

        jButtonSaveAs.setText("Save as");
        jButtonSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveAsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldPath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonOpen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSaveAs, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonOpen)
                    .addComponent(jButtonSaveAs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOpenActionPerformed
        // open file dialog
        JFileChooser chooser = new JFileChooser(currentPath); 
        chooser.setDialogTitle(SELECT_SET_TITLE);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("XML", "xml");
        chooser.setFileFilter(filter);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            // update path text field
            String path = chooser.getSelectedFile().toString();
            jTextFieldPath.setText(path);

            // check if file exists
            File file = new File(path);
            if (!file.exists()) {
                JOptionPane.showMessageDialog(null, "Invalid path: " + path, "File not found!", JOptionPane.ERROR_MESSAGE);
                jTextFieldPath.setText(currentPath);
                return;
            }

            currentPath = path;
            
            // load card set
            CardSet set = new CardSet(file);
            jTextFieldSetName.setText(set.getName());
            jFormattedTextFieldTextSize.setValue(set.getTextSize());
            
            // load each card to ComboBox
            jComboBoxCard.removeAllItems();
            set.getCards().forEach(card -> {
                jComboBoxCard.addItem(card);
            });
        }
    }//GEN-LAST:event_jButtonOpenActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        save();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    /**
     * Save current card set.
     */
    private void save() {
        // get all cards in ComboBox
        List<Card> cards = new ArrayList<>();
        for (int i = 0; i < jComboBoxCard.getItemCount(); ++i) {
            cards.add(jComboBoxCard.getItemAt(i));
        }
        
        // save to xml file
        File file = new File(jTextFieldPath.getText());
        new CardSet(jTextFieldSetName.getText(), getTextSizeValue(), cards).save(file);
    }
    
    /**
     * Get text size from corresponding text field
     * @return text size
     */
    private float getTextSizeValue() {
        // if textfield empty set to default value
        if (jFormattedTextFieldTextSize.getText().equals("")) {
            jFormattedTextFieldTextSize.setValue(CardSet.DEFAULT_TEXT_SIZE);
        }
        return Float.valueOf(jFormattedTextFieldTextSize.getText());
    }
    
    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // add empty card
        jComboBoxCard.addItem(new Card("", ""));
        jComboBoxCard.setSelectedIndex(jComboBoxCard.getItemCount() - 1);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // remove currently selected card
        int index = jComboBoxCard.getSelectedIndex();
        if (index != -1) {
            jComboBoxCard.removeItemAt(index);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jComboBoxCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCardActionPerformed
        Card card = (Card) jComboBoxCard.getSelectedItem();
        if (card != null) {
            // set textfields corresponding to card selected
            jTextAreaFront.setText(card.front);
            jTextAreaBack.setText(card.back);
            jTextFieldID.setText(card.id);
            
            // enable components when a card is selected
            jTextAreaFront.setEnabled(true);
            jTextAreaBack.setEnabled(true);
            jTextFieldID.setEnabled(true);
            jButtonDelete.setEnabled(true);
            jButtonApply.setEnabled(true);
        } else {
            // empty textfield
            jTextAreaFront.setText("");
            jTextAreaBack.setText("");
            jTextFieldID.setText("");
            
            // disable components when no card selected
            jTextAreaFront.setEnabled(false);
            jTextAreaBack.setEnabled(false);
            jTextFieldID.setEnabled(false);
            jButtonDelete.setEnabled(false);
            jButtonApply.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBoxCardActionPerformed

    private void jButtonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApplyActionPerformed
        // apply changes to card
        Card card = (Card)jComboBoxCard.getSelectedItem();
        card.front = jTextAreaFront.getText();
        card.back = jTextAreaBack.getText();
        card.id = jTextFieldID.getText();
        
        // Update ComboBox to show changes
        jComboBoxCard.updateUI();
    }//GEN-LAST:event_jButtonApplyActionPerformed

    private void jButtonSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveAsActionPerformed
        // choose file to save
        JFileChooser chooser = new JFileChooser(currentPath); 
        chooser.setDialogTitle(SAVE_SET_TITLE);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("XML", "xml");
        chooser.setFileFilter(filter);
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            // update text field and save
            String path = chooser.getSelectedFile().toString();
            jTextFieldPath.setText(path);
            save();
        }
    }//GEN-LAST:event_jButtonSaveAsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlashCardsEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlashCardsEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlashCardsEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlashCardsEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlashCardsEditorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonApply;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonOpen;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSaveAs;
    private javax.swing.JComboBox<Card> jComboBoxCard;
    private javax.swing.JFormattedTextField jFormattedTextFieldTextSize;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelFront;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelSetName;
    private javax.swing.JLabel jLabelTextSize;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBack;
    private javax.swing.JPanel jPanelFront;
    private javax.swing.JScrollPane jScrollPaneBack;
    private javax.swing.JScrollPane jScrollPaneFront;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextAreaBack;
    private javax.swing.JTextArea jTextAreaFront;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPath;
    private javax.swing.JTextField jTextFieldSetName;
    // End of variables declaration//GEN-END:variables
}
